# Site settings
title: "Andrea Maglie"
description: "Software Engineer, guitar player. Founder of GDG (Google Developer Group) Venice."
#url: 'http://andreamaglie.com'
url:  http://localhost:4000
baseurl: ''
google_analytics: 'UA-48681711-2'
disqus_shortname: 'techisfunit'

author:
  name: 'Andrea Maglie'
  email: andrea.maglie@gmail.com
  twitter_username: techisfun
  #facebook_username: joshgerdes
  github_username:  techisfun
  linkedin_username:  andreamaglie
  playstore_link: http://bit.ly/1bISG1K

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-gist

gems: ['jekyll-paginate', 'jekyll-gist']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
